#!/bin/bash

# NOTE: this file used to source os/utils.sh to get get_os(), whose result was
# never used. Sourcing it leaked the whole installer toolkit (mkd, execute,
# ask, print_*, ...) into every interactive shell.

# ----------------------------------------------------------------------

alias t='vim ~/todo.txt'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e='vim'
alias g='git'
alias ll='ls -l'
alias m='man'
alias map='xargs -n1'
alias q='exit'

# IP addresses
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

## Paul Irish ls stuff
## (the coreutils `gls` fallback and CLICOLOR_FORCE were macOS-only and are gone)

# ls options: A = include hidden (but not . or ..), F = put `/` after folders, h = byte unit suffixes
# --color=auto so piping to awk/grep below doesn't get escape codes
alias ls='ls -AFh --color=auto --group-directories-first'

# List ALL files (colorized() in long format, show permissions in octal
alias la="ls -l | awk '
{
  k=0;
  for (i=0;i<=8;i++)
    k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));
  if (k)
    printf(\"%0o \",k);
  printf(\" %9s  %3s %2s %5s  %6s  %s %s %s\n\", \$3, \$6, \$7, \$8, \$5, \$9,\$10, \$11);
}'"

# List only directories
alias lsd='ls -l | grep "^d"'

# # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# # here's LS_COLORS
# # github.com/trapd00r/LS_COLORS
eval "$(dircolors -b ~/.dircolors)"
