#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

    local file=''
    local i=''

    declare -r -a FILES_TO_SOURCE=(
        'bash_aliases'
        'bash_autocomplete'
        'bash_exports'
        'bash_functions'
        'bash_options'
        'bash_prompt'
        'bash.local'  # for local settings that should
                      # not be under version control
    )

    for i in ${!FILES_TO_SOURCE[*]}; do
        file="$HOME/.${FILES_TO_SOURCE[$i]}"
        [ -r "$file" ] && source "$file"
    done

}

source_bash_files
unset -f source_bash_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use dotfiles specific executibles
PATH=~/projects/dotfiles/bin:$PATH

# Use locally-installed npm executables
PATH=./node_modules/.bin:~/npm/bin:$PATH

source ~/projects/dotfiles/bin/z/z.sh

export NVM_DIR="$HOME/projects/dotfiles/bin/nvm"
source "$NVM_DIR/nvm.sh" # This loads nvm

PATH=~/.local/bin:$PATH

PATH=/usr/local/texlive/2021/bin/x86_64-linux:$PATH
MANPATH=/usr/local/texlive/2021/texmf-dist/doc/man:$MANPATH 
INFOPATH=/usr/local/texlive/2021/texmf-dist/doc/info:$INFOPATH 

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# activate git auto complete
# http://apple.stackexchange.com/questions/55875/git-auto-complete-for-branches-at-the-command-line/55886#55886
. git-completion.bash
