#!/bin/bash

# Shell Variables
# http://linux.die.net/man/1/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make vim the default editor
export EDITOR='vim'

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines of history
# persisted in the Bash history file (default value is 500)
export HISTFILESIZE=10000

# Don't add certain commands to the history file
export HISTIGNORE='&:[bf]g:c:clear:history:exit:q:pwd:* --help'

# Increase the maximum number of commands recorded in the
# command history (default value is 500)
export HISTSIZE=10000

# Increase the maximum number of lines of history persisted
# in the `Node` REPL history file (default value is 1000)
# https://github.com/nodejs/node/blob/a85f4b5ce5791caf8caa9b31970313c6183a5499/doc/api/repl.markdown#persistent-history
export NODE_REPL_HISTORY_SIZE=10000

# NOTE: `history -a` used to be set here via PROMPT_COMMAND, but bash_prompt
# is sourced later and assigns PROMPT_COMMAND outright, so it never ran.
# It now lives in prompt_command() in bash_prompt.

# Prefer US English and use UTF-8 encoding.
#
# LANG is the fallback for every LC_* category, so it carries the charset.
# LC_ALL is deliberately NOT set: it outranks every individual category and
# can't be selectively overridden, which is why it's meant for one-off use
# (`LC_ALL=C sort`) rather than a profile. It also used to paper over LANG
# being 'en_US' here - a locale this system doesn't even generate - so
# anything that cleared LC_ALL dropped the shell to non-UTF-8.
export LANG='en_US.UTF-8'

# highlighting inside manpages and elsewhere
# https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# Don't clear the screen after quitting a man page
export MANPAGER='less -X'

# Default FZF (basically grab everything except node node and git)
export FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*}"'
