#!/bin/bash

declare DOTFILES_DIR_PATH="$(dirname $(dirname $(readlink $BASH_SOURCE)))"

source "$DOTFILES_DIR_PATH/os/utils.sh" \
    && declare OS="$(get_os)"

# ----------------------------------------------------------------------

# Editor
which subl &> /dev/null
if [ $? -ne 0 ]; then # if last command exit code was not good
  # look for subl on osx
  if [ -f /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl ]
    then
      alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -W'
  else
  	alias subl='echo "Sublime text not found"'
  fi
fi



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e='vim'
alias g='git'
alias ll='ls -l'
alias m='man'
alias map='xargs -n1'
alias q='exit'

# IP addresses
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

## Paul Irish ls stuff

###
# time to upgrade `ls`

# use coreutils `ls` if possible…
hash gls >/dev/null 2>&1 || alias gls="ls"

# always use color, even when piping (to awk,grep,etc)
if gls --color > /dev/null 2>&1; then colorflag="--color"; else colorflag="-G"; fi;
export CLICOLOR_FORCE=1

# ls options: A = include hidden (but not . or ..), F = put `/` after folders, h = byte unit suffixes
alias ls='gls -AFh ${colorflag} --group-directories-first'
alias lsd='ls -l | grep "^d"' # only directories
#    `la` defined in .functions
###

# List ALL files (colorized() in long format, show permissions in octal
alias la="ls -l | awk '
{
  k=0;
  for (i=0;i<=8;i++)
    k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));
  if (k)
    printf(\"%0o \",k);
  printf(\" %9s  %3s %2s %5s  %6s  %s %s %s\n\", \$3, \$6, \$7, \$8, \$5, \$9,\$10, \$11);
}'"

# List only directories
alias lsd='ls -l | grep "^d"'

# # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# # here's LS_COLORS
# # github.com/trapd00r/LS_COLORS
if command -v gdircolors >/dev/null 2>&1; then
    eval "$(gdircolors -b ~/.dircolors)"
else
    eval "$(dircolors -b ~/.dircolors)"
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
unset OS
